const DUMMY_AVATAR_URL = `${process.env.DUMMY_AVATAR_URL}`;
const DEFAULT_NUM_OF_QUESTIONS = 15;
const DEFAULT_QUESTION_DIFFICULTY = 'any';
const EASY_QUESTION_POINTS = 10;
const MEDIUM_QUESTION_POINTS = 15;
const HARD_QUESTION_POINTS = 20;
const DEFAULT_BACKGROUND_MUSIC = 'on';
const DEFAULT_SOUND_EFFECTS = 'on';
const TIME_PER_QUESTION = 30000;
const HOME_BANNER_UNIT_ID = 'ca-app-pub-6155362875273384/6523987929';
const HOME_INTERSTITIAL_UNIT_ID = 'ca-app-pub-6155362875273384/7209549487';

export {
  DUMMY_AVATAR_URL,
  DEFAULT_NUM_OF_QUESTIONS,
  DEFAULT_QUESTION_DIFFICULTY,
  EASY_QUESTION_POINTS,
  MEDIUM_QUESTION_POINTS,
  HARD_QUESTION_POINTS,
  DEFAULT_BACKGROUND_MUSIC,
  DEFAULT_SOUND_EFFECTS,
  TIME_PER_QUESTION,
  HOME_BANNER_UNIT_ID,
  HOME_INTERSTITIAL_UNIT_ID,
};
