const DUMMY_AVATAR_URL = 'https://i.pravatar.cc/100';
const DEFAULT_NUM_OF_QUESTIONS = 15;
const DEFAULT_QUESTION_DIFFICULTY = 'any';
const EASY_QUESTION_POINTS = 10;
const MEDIUM_QUESTION_POINTS = 15;
const HARD_QUESTION_POINTS = 20;
const DEFAULT_BACKGROUND_MUSIC = 'on';
const DEFAULT_SOUND_EFFECTS = 'on';

export {
  DUMMY_AVATAR_URL,
  DEFAULT_NUM_OF_QUESTIONS,
  DEFAULT_QUESTION_DIFFICULTY,
  EASY_QUESTION_POINTS,
  MEDIUM_QUESTION_POINTS,
  HARD_QUESTION_POINTS,
  DEFAULT_BACKGROUND_MUSIC,
  DEFAULT_SOUND_EFFECTS,
};
