const DUMMY_AVATAR_URL = 'https://i.pravatar.cc/100';
const DEFAULT_NUM_OF_QUESTIONS = 15;
const DEFAULT_QUESTION_DIFFICULTY = 'any';

export {
  DUMMY_AVATAR_URL,
  DEFAULT_NUM_OF_QUESTIONS,
  DEFAULT_QUESTION_DIFFICULTY,
};
